logging:
  level:
    org:
      springframework:
        security: debug
security:
  sessions: NEVER
server:
  address: 127.0.0.1
  port: 9000
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
