logging:
  level:
    org.springframework.security: DEBUG
security:
  user:
    role: USER,ADMIN
  ignored:
  - "*.bundle.*"
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
server:
  port: 8082
